from .config import CUDA, MPI, MATLAB, LINK_SCIPION, CC, CXX, CUDA_COMPILER

DEFAULT_CMAKE = 'cmake'

# CMake cache file variables to look for
XMIPP_USE_CUDA=CUDA
XMIPP_USE_MPI=MPI
XMIPP_USE_MATLAB=MATLAB
XMIPP_LINK_TO_SCIPION=LINK_SCIPION
CMAKE_BUILD_TYPE='CMAKE_BUILD_TYPE'
CMAKE_C_COMPILER=CC
CMAKE_CXX_COMPILER=CXX
CMAKE_CUDA_COMPILER=CUDA_COMPILER

# CMake saved version variables
CMAKE_PYTHON = 'Python3'
CMAKE_CUDA = 'CUDA'
CMAKE_MPI = 'MPI'
CMAKE_HDF5 = 'HDF5'
CMAKE_JPEG = 'JPEG'
CMAKE_SQLITE = 'SQLite3'
CMAKE_JAVA = 'Java'
CMAKE_CMAKE = 'CMake'
CMAKE_GCC = 'CC'
CMAKE_GPP = 'CXX'
