name: Test xmipp installation
on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install project
        working-directory: ${{ github.workspace }}
        run: pip install .
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfftw3-dev libopenmpi-dev libhdf5-dev libtiff5-dev libsqlite3-dev default-jdk git cmake openmpi-bin gcc g++
          pip install numpy
      
      - name: Clone xmipp
        working-directory: ${{ github.workspace }}/../
        run: git clone https://github.com/I2PC/xmipp.git
      
      - name: Set config variables
        run: echo "SEND_INSTALLATION_STATISTICS=OFF\nBUILD_TESTING=OFF" > xmipp.conf
      
      - name: Install xmipp
        working-directory: ${{ github.workspace }}/../xmipp
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: ./xmipp all -b $BRANCH_NAME --keep-output || (cat compilation.log && false)
